name: Testing Acttion

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Coverage
        run: > 
          mvn sonar:sonar 
          -Dsonar.organization=${{vars.SONAR_ORG}} 
          -Dsonar.projectKey=${{vars.SONAR_PROJECT_KEY}} 
          -Dsonar.host.url=${{vars.SONAR_HOST_URL}} 
          -Dsonar.login=${{secrets.SONAR_TOKEN}}
      - name: List files
        run: ls -R
    
